query suggestionSearches($term: String!) {
  suggestionSearches(term: $term) {
    searches {
      term
      attributes {
        key
        value
        labelKey
        labelValue
      }
    }
  }
}
